### 메뉴조회 HTTP 요청

GET http://127.0.0.1:8080/api/member/register
Content-Type: application/json

{
"id": 4,
"storeId": 3,
"title": "불고기덮밥2",
"content": "달콤한 불고기와 밥, 김치 포함",
"price": 8500,
"thumbnail": "https://example.com/images/bulgogi.jpg"
}

